DROP TABLE IF EXISTS instas CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS instas_tags;

CREATE TABLE instas (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  description TEXT,
  img TEXT NOT NULL
);

CREATE TABLE tags (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  tag TEXT NOT NULL
);

CREATE TABLE instas_tags (
  insta_id BIGINT REFERENCES instas(id),
  tag_id BIGINT REFERENCES tags(id),
  PRIMARY KEY(insta_id, tag_id)
);